feat: vex-markdown component
DEIPworld/deip-modules pull request #128
Opened 2021-08-05 07:15 UTC by McWild

https://app.asana.com/0/1199229333810002/1200712364863283/f

2021-08-05 10:50 UTC, euheny requested changes

2021-08-05 10:50 UTC, euheny commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +  <vex-stack gap="32">
зачем стакер? чайлд же только один

2021-08-05 10:50 UTC, euheny commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +      source: {
для пропсов более чем достаточно сурса и опшенов как объект. нахлобучивать все и всея в виде отдельных пропов крайне непродуктивно

2021-08-05 10:50 UTC, euheny commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        marked.setOptions({
соответственно тутачки проверяем проп опшенов и сетим

2021-08-05 10:50 UTC, euheny commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        return DOMPurify.sanitize(marked(this.source));
маркед уже имеет в своем составе санитайзер. зачем дополнительный огород огородить?

2021-08-05 10:50 UTC, euheny commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        marked.setOptions({
да и каждый раз при вызове компьютеда такое себе сетить конфиг. как минимум достаточно иметь инстанс и в момент крита закинуть ему опшены. заодно проверить не фризится ли маркед, чтоб в каждом инстансе компонента создавался новый инстант парсера (ибо если инстанс один, то опшены разползутся на всю прилагу)

2021-08-05 12:58 UTC, McWild commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        return DOMPurify.sanitize(marked(this.source));
судя по всему депрекейтнули
теперь рекомендуют использовать сторонний санитайзер

2021-08-05 12:58 UTC, McWild commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        marked.setOptions({
так и есть, истанс создаётся один.

2021-08-05 12:58 UTC, McWild commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +      source: {
переделал

2021-08-05 12:58 UTC, McWild commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +  <vex-stack gap="32">
убрал

2021-08-05 13:35 UTC, McWild commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        marked.setOptions({
Может пока перенести сеттинг опшенов в компьютед?
Тогда будет возможность на одной странице выводить превью с разными настойками вывода в разных окнах, если понадобится.

2021-08-05 18:28 UTC, euheny commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        marked.setOptions({
инстанс самого парсера один или нет? сеттинги задефайененые в одном компоненте шарятся на все или остаются локально? это очень важно чтобы как раз таки можно было пользовать несколько компонентов на одной странице. в компьютеде держать сеттинги имеет смысл только при условии наличию дефалтовых и мержа их с внешними. сам парсер создавать в компьютеде очень накладно по перформансу

2021-08-05 18:34 UTC, euheny commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        marked.setOptions({
и по поводу тех же сеттингов - нафиг они нам реактивные? это к вопросу о компьютеде. тут скрее в крите их можно засетить и в маркед и бахнуть его инстанс в дату. главное чтоб не потерло другие вызовы на странице

2021-08-05 18:50 UTC, euheny commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        marked.setOptions({
как бы вот: `marked(markdownString [,options] [,callback])` и не надо никакого компьютеда. варианты:
- копьютед который возвращает маркед с забросом пропсов вместо всяких  сетопшенов чтобы не бить основной инстанст если он один
- render() метод компонента где все это дело происходит - можно как пропс так и слот туда кидать для вывода.

эт при условии что инстанс маркеда в виде синглтона

2021-08-06 08:43 UTC, McWild commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        marked.setOptions({
> инстанс самого парсера один или нет? сеттинги задефайененые в одном компоненте шарятся на все или остаются локально? это очень важно чтобы как раз таки можно было пользовать несколько компонентов на одной странице. в компьютеде держать сеттинги имеет смысл только при условии наличию дефалтовых и мержа их с внешними. сам парсер создавать в компьютеде очень накладно по перформансу

Инстанс один.
Сеттинги шарятся на все компоненты.

2021-08-06 09:30 UTC, euheny commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        marked.setOptions({
ну тогда вариант только ретурнить рендер сразу с сетингами а не сетить их для инстанса

2021-08-09 06:43 UTC, euheny requested changes

2021-08-09 06:43 UTC, euheny commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        DOMPurify.sanitize(marked(this.source, this.options))
1 - сделать сет дефалтовых настроек
2 - санитайзер УЖЕ есть в составе маркеда

2021-08-09 07:02 UTC, McWild commented on packages/plugins/VuetifyExtended/lib/components/VexMarkdown/VexMarkdown.vue
> +        DOMPurify.sanitize(marked(this.source, this.options))
1. готово
2. депрекейтнули

2021-08-09 07:10 UTC, euheny approved these changes

2021-08-09 07:11 UTC, merged