fix: fixed data auto update on the fundraising widget
DEIPworld/deip-modules pull request #204
Opened 2021-09-30 06:37 UTC by Vadim-SVB

Fixed auto-update of **Fundraising widget**
Now the widget updates data depending on the type of state in which it is,
 for the time that can be set by the "autoUpdateTime" props (by default 1 minute)

2021-09-30 06:57 UTC, euheny commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +      this.getProjectTokenSaleData();
метод на сделает паузу потока и лодинг просто перещелкнется не дожидаясь данных

2021-09-30 06:57 UTC, euheny commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +        if (status === TS_TYPES.INACTIVE) this.$store.dispatch('fundraising/getListByProjectId', this.projectId);
мне кажетс такие варианты удобнее через деструкцию писать.
```const { ACTIVE, EXPIRED } = TS_TYPES```
не придется копипастить

2021-09-30 07:34 UTC, elena-vlasova commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +        if (status === TS_TYPES.INACTIVE) this.$store.dispatch('fundraising/getListByProjectId', this.projectId);
`const { ACTIVE, EXPIRED } = TS_TYPES`
не видела, что бы мы так с енамами делали

2021-09-30 07:34 UTC, elena-vlasova commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +        return null;
Для чего null возвращается?

2021-09-30 07:34 UTC, elena-vlasova commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +        if (status === TS_TYPES.INACTIVE) this.$store.dispatch('fundraising/getListByProjectId', this.projectId);
Стоит добавить ` .catch((error) => {
            console.error(error);
          })`

2021-09-30 07:37 UTC, euheny commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +        if (status === TS_TYPES.INACTIVE) this.$store.dispatch('fundraising/getListByProjectId', this.projectId);
> `const { ACTIVE, EXPIRED } = TS_TYPES` не видела, что бы мы так с енамами делали

просто как предложение, но более

2021-09-30 08:34 UTC, Vadim-SVB commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +      this.getProjectTokenSaleData();
Согласен, выпилил его, потому что есть проверка в finally самой функции

2021-09-30 08:37 UTC, elena-vlasova commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +      this.getProjectTokenSaleData();
Лучше из функции выпилить и добавить сюда. Раз уже сетится loading=true не в методе получения данных

2021-09-30 08:37 UTC, Vadim-SVB commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +        if (status === TS_TYPES.INACTIVE) this.$store.dispatch('fundraising/getListByProjectId', this.projectId);
Женя прав, работает так же хорошо и выглядит приятно, нужно было сразу так сделать
Мне хочется поменять

Да ты права, добавил .catch((error) => { console.error(error); })

2021-09-30 08:55 UTC, elena-vlasova commented
Еще замечание. В deip-modules в названиях коммитов надо указывать название модуля, к которому коммит относится `chore(@deip/fundraising-module): ...`

2021-09-30 11:30 UTC, Vadim-SVB commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +      this.getProjectTokenSaleData();
Думаю теперь хорошо, вначале есть загрузка , потом нет

2021-09-30 12:10 UTC, elena-vlasova commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +      this.getProjectTokenSaleData().then(()=>{
loading лучше выключать в finally

2021-09-30 12:14 UTC, Vadim-SVB commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +      this.getProjectTokenSaleData().then(()=>{
Окей резонно, исправлю

2021-09-30 12:42 UTC, elena-vlasova approved these changes

2021-09-30 14:38 UTC, euheny requested changes

2021-09-30 14:38 UTC, euheny commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +        if (status === INACTIVE) {
отработают все проверки. в идеале при активе делать дефалтовый ретурн и в ифаг условные
```
if (a) return aa();
if (b) return bb();
return default()
```

2021-09-30 17:08 UTC, Vadim-SVB commented on packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
> +        if (status === INACTIVE) {
Отличная идея, лучше чем null возвращать )
Поправим

2021-10-01 08:00 UTC, elena-vlasova approved these changes

2021-10-01 08:04 UTC, merged