docs: added document on principles and agreements in the project
DEIPworld/deip-modules pull request #258
Opened 2021-10-27 12:56 UTC by sholohov

- the document for contributing has been moved to the root directory

2021-11-01 06:53 UTC, sholohov commented on docs/principles-and-agreements.md
> +  - именовать vue файл в `kebab-case` пример `custom-component.vue`
> если для компонента помимо его самого надо вспомогашки:
> 
> ...
> component-name.json
> component-name.xxx
> ?

Я так думаю, не стоит мешать логику, данные и представление, vue-компонент, по сути - это представление и минимум логики, т.е. если есть папка components, там должны быть именно компоненты, данные, конфиги - другая ответственность, должны находится на уровне дата провайдера и конфигов соответственно.
Считаю нужно установить чёткие границы ответственности:
- `dataProvider`, `services` - отвечают за предоставление данных и методы для работы с ними, там же находятся моки.
- `components` - vue-компоненты, 1-файловые или 2-файловые, представление - шаблон+стили и js-логика
- `plugins` - кросс-проектные вспомогательные функции
- `config` - конфигурации, переменные для настройки приложения в зависимости от окружения
Это основные ответственности, про остальные - другой разговор.

2021-11-01 07:06 UTC, sholohov commented on docs/principles-and-agreements.md
> +  - именовать vue файл в `kebab-case` пример `custom-component.vue`
Если в директории `component` должны лежать vue-компоненты, 1-файловые или 2-файловые, представление - шаблон+стили и js-логика, то есть у меня есть несколько вариантов:

2021-11-01 07:15 UTC, sholohov commented on docs/principles-and-agreements.md
> +  - именовать vue файл в `kebab-case` пример `custom-component.vue`
Если в директории component должны лежать vue-компоненты, 1-файловые или 2-файловые, представление - шаблон+стили и js-логика, предлагаю несколько вариантов:
вариант 1:
```
comonents
    СomponentOne.vue // 1-файловый компонент
    СomponentTwo // 2-файловый компонент
        сomponentTwo.js
        сomponentTwo.sass
```
вариант 2:
```
comonents
    СomponentOne.vue // 1-файловый компонент
    СomponentTwo // 2-файловый компонент
        сomponent-two.js
        сomponent-two.sass
```
вариант 3:
```
comonents
    сomponent-one.vue // 1-файловый компонент
    сomponent-two // 2-файловый компонент
        сomponent-two.js
        сomponent-two.sass
```

я за 1, 2

2021-11-01 08:48 UTC, euheny commented on docs/principles-and-agreements.md
> +  - именовать vue файл в `kebab-case` пример `custom-component.vue`
обсудим на дэйли

2021-11-01 08:48 UTC, euheny commented on docs/principles-and-agreements.md
> +  происходит по схеме `function [action][triger][event] () { ... }`, `event` - может не быть:
обсудим на дэйли

2021-11-01 08:51 UTC, euheny commented on docs/principles-and-agreements.md
> +- **[Styleguide по Markdown](https://arcticicestudio.github.io/styleguide-markdown/)** -
1 - маркдаун не настолько адово гибкий, чтобы упарываться на его гайды
2 - я бы разделял файлы
3 - как предложение (не только к этой доке) можно взять airbnb как основу гайдов и по возможности тащить данные отуда (касательно всех зон) тем более что и линтер у нас оттуда частично

2021-11-02 15:07 UTC, sholohov commented
changelog: updated agreement points

- removed agreement for .md documentation
- updated agreement for event handlers
- updated agreement for component identity and names collision

2021-11-03 07:30 UTC, euheny requested changes
в дальнейшем надо будет части этой доки или перегреппировать или перенести, чтобы оталась информация только касательная srp

2021-11-03 07:30 UTC, euheny commented on docs/principles-and-agreements.md
> +  automation
думаю этот блок стоит выпилить и перенести в раздел нэйминга

2021-11-03 08:11 UTC, sholohov commented on docs/principles-and-agreements.md
> +  automation
Ок. Но что б не сочинять дважды, может закинь куда-нибудь себе в доку, прежде чем я уберу отсюда

2021-11-03 08:34 UTC, euheny commented on docs/principles-and-agreements.md
> +  automation
может замутить вайл типа _temp-agregate.md и туда все пихать, а же в конечных файлах оставлять только тематическое?

2021-11-03 08:44 UTC, sholohov commented on docs/principles-and-agreements.md
> +  automation
Поддерживаю. Переименую файл. Может как-то в одной ветке на доками работать?

2021-11-03 08:47 UTC, euheny commented on docs/principles-and-agreements.md
> +  automation
пока из своей все впили. потм возможно и в одной. я сейчас смотрю варианты нормльного ui для этого дела, так что скоро совсем определимся как оно все будет

2021-11-03 08:50 UTC, elena-vlasova commented on docs/principles-and-agreements.md
> +  │   │   AutomationRuleSetup-item.vue
Почему item через дефис написано?

2021-11-03 11:44 UTC, sholohov commented on docs/principles-and-agreements.md
> +  │   │   AutomationRuleSetup-item.vue
Спасибо. Не заметил, когда из кебеба конвертировал

2021-11-05 07:32 UTC, euheny commented
ты вообще получается примеры выпилил из доки по ответственности?

2021-11-05 10:34 UTC, sholohov commented
> ты вообще получается примеры выпилил из доки по ответственности?

Да. Мы ж вроде уже решили, что размещаем только соглашение о том что мы юзаем SRP и даём ссыль на доку гугла, если тема интересна пусть сам гуглит, что нет смысла давать кучу примеров, если по этому есть масса статей. Пример был в соглашениях "один метод - одно действие (группировка действий)" это что-то около темы и только про методы, этого мало, после того, как вынес SRP и Декомпозицию в отдельную доку, удалил.

2021-11-08 05:52 UTC, sholohov commented
Добавил пример для SRP

2021-11-08 09:45 UTC, euheny approved these changes

2021-11-08 09:45 UTC, merged