fix(@deip/layouts-module):fix delete row on layout-settings page
DEIPworld/deip-modules pull request #283
Opened 2021-11-16 12:59 UTC by Vadim-SVB

Schema lines can now be deleted

2021-11-17 13:04 UTC, euheny requested changes

2021-11-17 13:04 UTC, euheny commented on packages/modules/layouts/lib/components/settings/layout-settings.js
> +          <VCol staticClass="d-flex justify-end col col-1">
отступ (таб) для кнопки

2021-11-18 11:10 UTC, Vadim-SVB commented on packages/modules/layouts/lib/components/settings/layout-settings.js
> +          <VCol staticClass="d-flex justify-end col col-1">
Готово!

2021-11-19 07:52 UTC, euheny approved these changes

2021-11-19 07:53 UTC, merged