docs: added api specification
DEIPworld/deip-modules pull request #288
Opened 2021-11-19 08:28 UTC by sholohov

2021-11-19 08:36 UTC, euheny commented on docs/api-secification.md
> +
meta же к корню документа относится, а не к апи? или это мета апи? тогда что-то много меты )

2021-11-19 08:36 UTC, euheny commented on docs/api-secification.md
> +  },
тагда еще и  инфу о сортинге неплохо бы получать для полноты картины

2021-11-19 08:36 UTC, euheny commented on docs/api-secification.md
> +
была идея иметь статус респонса при любом раскладе в корне документа. решил отказаться или забыл?

2021-11-19 08:50 UTC, sholohov commented on docs/api-secification.md
> +
Да, судя из доков JSON:API  такое поле может быть в любой сущности (кроме самих ресурсов, конечно), такой своеобразный зарезервированный объект под  всякую нестандартную инфу, видимо что бы был чистый шаблон, мне такой подход нравится.

2021-11-19 08:51 UTC, sholohov commented on docs/api-secification.md
> +  },
Ага. Добавил.

2021-11-19 09:03 UTC, sholohov commented on docs/api-secification.md
> +
В доках JSON:API вычитал, что при ошибке не может быть данных, они так решили, но судя по популярности соглашения, они в этом что-то понимают, вот и я задумался.

По сути можно и статуса.
`success` - есть поле `data`, нет `error`
`error` - есть поле `error`, нет `data`
`fail` -  есть поле `data`, нет `error`, зато есть объект `failed`, где накидать ошибок 

Такой подходя я уже использовал, это удобно, можно проверить наличие поля, если есть, вывести его содержимое предварительно отформатировав в читабельном виде или сформировать файл для скачивания например csv или большой, что бы посмотреть в каком вьвере

2021-11-22 12:27 UTC, elena-vlasova commented on docs/api-secification.md
> +Объект ресурса **ДОЛЖЕН** содержать как минимум `id`.
Стоит ли тут упомянуть весь зоопарк наших айдишек _id, entityId, externalId?

2021-11-22 12:53 UTC, sholohov commented on docs/api-secification.md
> +Объект ресурса **ДОЛЖЕН** содержать как минимум `id`.
Главное только регламентировать единый id ресурса, остальное думаю уже специфично для каждой сущности.

2021-11-22 12:54 UTC, elena-vlasova commented on docs/api-secification.md
> +- `hasNext` - есть-ли следующая страница
Не вижу особого смысла в hasNext, там, где это нужно, можно высчитать на фронте, если возвращать totalPages и totalItems

2021-11-22 12:54 UTC, elena-vlasova commented on docs/api-secification.md
> +
Я бы тогда не выделяла отдельно `failed`, `error` достаточно

2021-11-22 12:54 UTC, elena-vlasova commented on docs/api-secification.md
> +Сортировка на сервере используется по умолчанию, если клиенту потребовалось её изменить, нужно передать дополнительный параметр `sort`, значением которого будет строка состоящая из 2-х частей разделё
Как будет выглядеть сортировка по нескольким полям? И вообще реально ли сделать сортировку по атрибутам?

2021-11-22 12:54 UTC, elena-vlasova commented on docs/api-secification.md
> +  },
Зачем инфа о сортинге в ответе, если она есть в запросе, как и номер текущей страницы и количество записей на странице?

2021-11-22 13:04 UTC, sholohov commented on docs/api-secification.md
> +  },
Хз зачем это в ответе сортинг. В респонсе по сути нужен только флаг, наличие след. страница, или общее кол-во записей. А в запросе уже передавать pageSize и cerentPage, sort - опционально, более точная выборка на основе filters.

2021-11-22 13:10 UTC, sholohov commented on docs/api-secification.md
> +
Согласен, для начала хватит и errors, только учесть при реализации, что бы по надобности можно было реализовать и failed, по аналогии.

2021-11-22 13:16 UTC, sholohov commented on docs/api-secification.md
> +- `hasNext` - есть-ли следующая страница
Добавил вариант для общей картины т.к. на моём прошлом проекте этот вариант, 1 - проще реализовывался на бэке и 2 - давал  больше перфоманса. Естественно, если есть totalPages или totalItems, с эти на много лучше и проще работать на фронте.

2021-11-22 13:29 UTC, sholohov commented on docs/api-secification.md
> +Сортировка на сервере используется по умолчанию, если клиенту потребовалось её изменить, нужно передать дополнительный параметр `sort`, значением которого будет строка состоящая из 2-х частей разделё
Как это возможно - сортировка по нескольким полям? Одновременно может быть только одно значение и одно направление. Т.е. ты передаёшь тот же атрибут, например он называется `name` и "по возрастанию" или "по убыванию". Фильтрацию может имеешь ввиду? Фильтрами, метафорически выражаясь, уже сокращаешь воронку и их уже может быть неограниченное кол-во.

2021-11-22 14:10 UTC, elena-vlasova commented on docs/api-secification.md
> +- `hasNext` - есть-ли следующая страница
Если это варианты для выбора, тогда я за totalPages и totalItems)

2021-11-22 14:20 UTC, elena-vlasova commented on docs/api-secification.md
> +Сортировка на сервере используется по умолчанию, если клиенту потребовалось её изменить, нужно передать дополнительный параметр `sort`, значением которого будет строка состоящая из 2-х частей разделё
Я именно про сортировку. Пример - [Data table вьютифая](https://vuetifyjs.com/en/components/data-tables/#multi-sort). 
Кстати, про фильтры в этом доке тоже можно  написать

2021-11-22 14:34 UTC, sholohov commented on docs/api-secification.md
> +- `hasNext` - есть-ли следующая страница
Как фронтенд, я тоже за totalPages и totalItems, если так будет, буду только рад )

2021-11-22 15:20 UTC, sholohov commented on docs/api-secification.md
> +Сортировка на сервере используется по умолчанию, если клиенту потребовалось её изменить, нужно передать дополнительный параметр `sort`, значением которого будет строка состоящая из 2-х частей разделё
Про вьютифай. Впервые такое встречаю, что б каждая последующая сортировка, устанавливает свой, более низкий приоритет и работает если у предыдущей есть одинаковые значения, в противном случае ничего изменить не может. Фича оч специфичная, на мой взгляд, можно запутать народ. Мне, лично не нравится такое.
В любом случае, мы обсуждаем возможности сервера, на сколько я успел познакомится с mysql, такое затруднительно сделать, т.к. там один параметр `order by`.

```
SELECT *
FROM Artists
ORDER BY Singer
``` 

Потом только фильтрация

```
SELECT Singer, Album, Year
FROM Artists
WHERE Year > 2005
ORDER BY Year DESC
```

Если это и возможно, то это будет сделать не сложно, добавив к основному параметру сортировки `sort=attributeName`, дополнительные `sort=attributeName:desc&sort=attributeNameTwo:desc&sort=attributeNameThree:desc`.

По опыту, даже для самых сложных выборок достаточно одной сортировки + уточнение с дополнительной фильтрацией. 

По поводу фильтрации, тема объёмная, много работы, нужно синхронизировать с возможностями на стороне сервера и сложно будет без ts, я бы добавил в проект типы, а пока юзать их через jsDoc. Задокументировать нужно будет обязательно, но отдельно.

2021-11-23 08:35 UTC, elena-vlasova commented on docs/api-secification.md
> +Сортировка на сервере используется по умолчанию, если клиенту потребовалось её изменить, нужно передать дополнительный параметр `sort`, значением которого будет строка состоящая из 2-х частей разделё
В mysql это делается так
```
ORDER BY
    column1 ASC,
    column2 DESC;
```
В mongodb тоже без проблем
```
{ $sort: { <field1>: <sort order>, <field2>: <sort order> ... } }
```

> на фронте это будет сделать не сложно, добавив к основному параметру сортировки sort=attributeName, дополнительные sort=attributeName:desc&sort=attributeNameTwo:desc&sort=attributeNameThree:desc

Тогда предлагаю добавить это в док на случай, если понадобится такая сортировка

2021-11-24 08:37 UTC, sholohov commented
- изменил описание сортировки
- изменил информацию по ошибкам

2021-11-24 08:52 UTC, sholohov commented
- изменил описание сортировки
- изменил информацию по ошибкам

2021-11-24 09:29 UTC, elena-vlasova commented on docs/api-secification.md
> +- `hasNext` - есть-ли следующая страница
Про hasNext дальше не будет обсуждения?)

2021-11-29 09:27 UTC, euheny commented on docs/api-secification.md
> +        details: {
для чего детали ошибки запиханы в отдельный объект?

2021-11-29 09:27 UTC, euheny commented on docs/api-secification.md
> +- `hasNext` - есть-ли следующая страница
hasNext под топор

2021-11-29 09:49 UTC, sholohov commented on docs/api-secification.md
> +- `hasNext` - есть-ли следующая страница
ok

2021-11-29 10:50 UTC, sholohov commented on docs/api-secification.md
> +        details: {
Если мы договорились о том, что будет использоваться массив объектов ошибок, то нам нужны служебные поля, тfкие как `index` - порядковый номер в ресурсах запроса, `name` - тип, для фильтрации и выбора действия и т.д. и саму ошибку, что бы избежать коллизии имён полей, саму ошибку нужно инкапсулировать в поле `details` - там уже может быть и объект и строка, это мы уже обработаем зная тип ошибки.
Я отталкивался от документации по JSON:API, там сделано такому же принципу, только я не понял, ошибку нужно в `details` или в `source` - https://jsonapi.org/format/#error-objects

2021-11-29 11:34 UTC, euheny requested changes

2021-11-29 11:34 UTC, euheny commented on docs/api-secification.md
> +        details: {
по факту ты перенес свой объект ошибок  на  уровень ниже не  изменив объект на основе нашего обсуждения и только усложнив структуру. в примере у тебя все поля сидят в одной ошибке что является какой-то  дичью
речь же шла о том, что каждое поле с каждой ошибкой является элементом массива

2021-11-29 11:41 UTC, euheny requested changes

2021-11-29 11:41 UTC, euheny commented on docs/api-secification.md
> +          type: "type is required",
про имя поля мы тоже разговаривали. поле-ключ не даст тебе возможности повесить несколько ошибок  на одно поле

2021-11-29 13:53 UTC, elena-vlasova reviewed
Можешь, плиз, добавить примеры респонсов с другими типами ошибок, кроме ошибок валидации? Не очень понимаю, как такой формат error ляжет на ошибки например 500, 404 или 401, что будет в errors?

2021-11-29 13:53 UTC, elena-vlasova commented on docs/api-secification.md
> +- `errors.locationType` - местоположение или часть запроса, вызвавшего ошибку. Используйте с, `location` чтобы определить ошибку. Например, если вы укажете недопустимое значение для параметра, `locat
Какие еще могут быть типы?

2021-11-29 13:53 UTC, elena-vlasova commented on docs/api-secification.md
> +- `errors.location` - конкретный элемент в пределах `locationType`, который вызвавший ошибку. Например, если вы укажете недопустимое значение для параметра, `location` будет имя параметра.
У меня location вызывает больше ассоциаций с географической локацией. Мб назвать `field` и `type`?

2021-11-29 14:47 UTC, sholohov commented on docs/api-secification.md
> +При возникновении ошибки на верхнем уровне **ДОЛЖЕН** присутствовать объект`error` с полями:
Это будет в структуре ошибки в поле `statusCode` можешь глянуть `class HttpError`. В объект можно будет запихнуть любую инфу из response headers.

2021-11-29 14:50 UTC, sholohov commented on docs/api-secification.md
> +- `errors.location` - конкретный элемент в пределах `locationType`, который вызвавший ошибку. Например, если вы укажете недопустимое значение для параметра, `location` будет имя параметра.
Брал всё у гуггла.
https://cloud.google.com/storage/docs/json_api/v1/status-codes#401-unauthorized

Ещё есть формат ошибки попроще от фэйсбука
https://github.com/cryptlex/rest-api-response-format#validation-error-formats

Похоже на то, о чём ты говоришь

2021-11-29 14:52 UTC, sholohov commented on docs/api-secification.md
> +- `errors.locationType` - местоположение или часть запроса, вызвавшего ошибку. Используйте с, `location` чтобы определить ошибку. Например, если вы укажете недопустимое значение для параметра, `locat
Слизал всё с гугла :)
https://cloud.google.com/storage/docs/json_api/v1/status-codes#401-unauthorized
Типы можно придумать по ходу того, какие будут потребности.

2021-11-29 14:55 UTC, sholohov commented on docs/api-secification.md
> +- `errors.location` - конкретный элемент в пределах `locationType`, который вызвавший ошибку. Например, если вы укажете недопустимое значение для параметра, `location` будет имя параметра.
Фишка в том, что location - это расположение, и то что там будет, зависит от locationType, возможно это путь через косую или путь до пол в объекте через точку, хз, т.е. более универсально, а field у фэйсбука - это поле, как будто-то кроме ошибок полей форм у них других не бывает

2021-11-29 14:56 UTC, elena-vlasova commented on docs/api-secification.md
> +- `errors.locationType` - местоположение или часть запроса, вызвавшего ошибку. Используйте с, `location` чтобы определить ошибку. Например, если вы укажете недопустимое значение для параметра, `locat
Можно было бы и поле `code` слизать тогда

2021-11-29 15:00 UTC, sholohov commented
> Можешь, плиз, добавить примеры респонсов с другими типами ошибок, кроме ошибок валидации? Не очень понимаю, как такой формат error ляжет на ошибки например 500, 404 или 401, что будет в errors?

Надо определиться Это нужно искать и сочинять,

2021-11-29 15:11 UTC, elena-vlasova commented on docs/api-secification.md
> +- `errors.location` - конкретный элемент в пределах `locationType`, который вызвавший ошибку. Например, если вы укажете недопустимое значение для параметра, `location` будет имя параметра.
Мне кажется, `errors` мы и будем скорее всего только для ошибок полей использовать. Тогда можно сразу определиться с форматом `field`. 
На примере 401 не вижу много смысла в этом поле.
```
 "locationType": "header",
 "location": "Authorization"
```

2021-11-30 07:07 UTC, sholohov commented on docs/api-secification.md
> +- `errors.location` - конкретный элемент в пределах `locationType`, который вызвавший ошибку. Например, если вы укажете недопустимое значение для параметра, `location` будет имя параметра.
Теоретически проект долгосрочный, сейчас "скорее всего только для ошибок полей", а завтра ещё что-то, шаблон ошибки должен быть универсальный, нужно заложить расширяемую структуру, как делают JSON:API, Google. Название field - я так понимаю, это имя ключа в структуре объекта, что сильно ограничивает его использование.

Т.к. у нас вето на структуру ошибок и учитывая зоопарк различных примеров, на мой взгляд, в объекте ошибки должно быть несколько обязательных полей, которые отвечающие на несколько вопросов: 
- "где ошибка?" - напрашивается"target" или "location"
- "как идентифицировать ошибку? какой тип?" - напрашивается "locationType" или "target"
- "какое содержимое ошибки?" - это может быть строка или массив строк, напрашивается "message[s]" и объект, хз, может и такое случиться, тогда напрашивается "src", "details", "value" и т.д.
"reason" - нужно что б абстрагироваться от сообщения об ошибки и сделать проверку на клиенте, возможно показать своё сообщение, подсветить цветом или открыть попап, хз.

Сейчас кажется, это лишние поля, но это минимальный задел на будущее, что бы потом не ломать голову, как переделать текущую структуру под другой тип ошибки. 

Если ошибки только для полей, то на мой взгляд самая оптимальная структура ошибки - повторяющая структуру запроса (объект ресурса или массив объектов ресурсов), вместо строки использовать массив строк `errors: [{ name: ["is required", "max length 30 char"] }]`, вместо индексов использовать пропуск элемента массива `errors: [object, , , , object]`  или null, т.е. `errors: [object, object, null,  null, null, object]` - просто, сжато, предсказуемо. Мы уже видели минималистичный референс - https://github.com/omniti-labs/jsend#fail

2021-12-01 07:51 UTC, euheny commented on docs/api-secification.md
> +- `errors.location` - конкретный элемент в пределах `locationType`, который вызвавший ошибку. Например, если вы укажете недопустимое значение для параметра, `location` будет имя параметра.
вчера с товарищем обсуждали локейшен и локейшен тайп. технически да - локейшен ассоциируется с географией, но если указывать и тайп типа пропс или хедер, то при связке field + fieldType мы получаем такое-же странное понимание в разрезе филдТайп = чекбокс (например) так что технически что так фигня что так. если забивать на  тайп, то field более чем достаточно

с точки зрения расширяемости данного ада я бы предложил такой вариант:

```
{
  code: Number, // error type (?Enum)
  message: String,
  location: String, // payload key
  locationType: String // optional, props/header, default (empty) = props -- (?Enum)
}
```

2021-12-01 08:01 UTC, euheny commented on docs/api-secification.md
> +- `errors.location` - конкретный элемент в пределах `locationType`, который вызвавший ошибку. Например, если вы укажете недопустимое значение для параметра, `location` будет имя параметра.
ps: в joi связка типа path + context

2021-12-02 08:36 UTC, sholohov commented on docs/api-secification.md
> +- `errors.location` - конкретный элемент в пределах `locationType`, который вызвавший ошибку. Например, если вы укажете недопустимое значение для параметра, `location` будет имя параметра.
По поводу location согласен, слово часто употребляется в простой речи в географическом контексте, в буквальном смысле, это ничто иное, как "место нахождения", в контексте ошибки - совсем другой смысл. Не могу, на самом деле подобрать лучшее слово для того, как описать "расположения ошибки". Если тип ошибки "property", например, то расположение будет имя "propName", если тип "object", то расположение "obj.key.subKey" или если тип "requestHeader", то расположение, например "Autorization", если тип "domain", то расположение, например "http://domain.com". Если это уже активно используется в гугле, то нам, считаю, это хороший задел на будущее и оно не сильно усложняет ни формирование ошибки, ни обработку. 

`code: Number, // error type (?Enum)` - это на подобие, "reason" который я предлагал?) Мне кажется строка с словом которое несёт смысл, будет полезнее цифры.

```typescript
type ResponseErrorItem = {
  reason: "invalid" | "invalidParameter" | "required";
  message: string | string []; // на случай если у поля несколько ошибок, в хэндлере один раз коде сделать
  location: string;
  locationType: string;
}
```
`Enum` я б отказался в пользу перечисляемых типов, это всегда понятно. Тип нужен только для исходников, компилятор не даст собрать если обнаружит несоответствие, а после он уберётся т.к. в js этого нет. При отсутствии ts, типы можно описывать через jsdoc:

```javascript
 /** @type { "invalid" | "invalidParameter" | "required" | string } */
const reason = ""
```
Но это отдельная тема разговора. Дальше:

`message: string | string [];` - массив на случай если у поля несколько ошибок, можно сделать по умолчанию массив, если у филда несколько месаджей ошибок, создавать 2 обекта ошибки ради 2-х сообщений, мне кажется лишне. Обработка происходит в раз написанном хэндлере и если если нужно показать все, можно `["error message 1", "error message 2"].join("; ")` и показать пользователю

2021-12-06 08:10 UTC, euheny commented on docs/api-secification.md
> +- `errors.location` - конкретный элемент в пределах `locationType`, который вызвавший ошибку. Например, если вы укажете недопустимое значение для параметра, `location` будет имя параметра.
про ризон можно и стринг, можно и код стандартизированнный @elena-vlasova @Vadim-SVB что скажете?

про массив в меседже я даже повторять не буду - это мы уже обсуждали и больше я к этой тебе возвращаться не намерен

2021-12-06 08:19 UTC, elena-vlasova commented on docs/api-secification.md
> +- `errors.location` - конкретный элемент в пределах `locationType`, который вызвавший ошибку. Например, если вы укажете недопустимое значение для параметра, `location` будет имя параметра.
Я бы пока только reason со строкой делала. Коды можно будет потом ввести, если понадобится

2021-12-09 07:50 UTC, Vadim-SVB approved these changes

2021-12-09 08:39 UTC, elena-vlasova commented on docs/api-secification.md
> +        message: "field is required",
В описании выше нет поля `message`

2021-12-09 08:39 UTC, elena-vlasova commented on docs/api-secification.md
> +        reason: "invalidArgument"
Сервер не будет выискивать такие поля, просто их не обработает. Можно убрать из примера

2021-12-09 08:39 UTC, elena-vlasova commented on docs/api-secification.md
> +    name: "BadRequest",
Всё-таки это BadRequest или ValidationError?

2021-12-09 08:54 UTC, sholohov commented on docs/api-secification.md
> +        message: "field is required",
Не понял, в каком описании нет поля?

2021-12-09 08:58 UTC, sholohov commented on docs/api-secification.md
> +        reason: "invalidArgument"
Ок, уберу.
Это был пример из жизни, когда ты ошибся с именем пропса и сервер говорит клиенту, мол, ты чувак, ты случайно не ошибся с именем ключа?
Игнорирование такого поля, тоже вариант.

2021-12-09 09:00 UTC, elena-vlasova commented on docs/api-secification.md
> +        message: "field is required",
Строки 36 - 40

2021-12-09 09:02 UTC, sholohov commented on docs/api-secification.md
> +    name: "BadRequest",
Всё зависит от того, что придёт с сервера, мы ещё не утверждали конкретных имён, в контексте доки это просто пример, написать ValidationError?

2021-12-09 09:03 UTC, sholohov commented on docs/api-secification.md
> +        message: "field is required",
Понял. Спасибо, добавлю.

2021-12-09 09:12 UTC, elena-vlasova commented on docs/api-secification.md
> +    name: "BadRequest",
Я думала, уже что-то примерно с бэком согласовывали. Раз нет, то можно оставить как есть

2021-12-13 10:37 UTC, elena-vlasova approved these changes

2021-12-13 11:21 UTC, egor-anikey approved these changes

2021-12-13 11:22 UTC, euheny approved these changes

2021-12-13 11:22 UTC, merged