All services refactor: update instance getter; added async
DEIPworld/deip-modules pull request #294
Opened 2021-11-23 08:14 UTC by sholohov

2021-11-23 08:55 UTC, euheny requested changes
```
import { createInstanceGetter } from '@deip/toolbox/lib/classSingleton';
```
сдвинуть экспорт/импорт до уровня тулбокса
```
import { createInstanceGetter } from '@deip/toolbox;
```

переименовать новый httpService - мы на рефакторинге не оставляем хвостов

2021-11-23 08:55 UTC, euheny commented on packages/services/AppConfig/lib/AppConfigService.js
> +export class AppConfigService {
добавь плиз камент на  депрекейтед. этот сервис артевакт

2021-11-23 08:55 UTC, euheny commented on packages/services/ExpertiseContributions/lib/ExpertiseContributionsHttp.js
>      const query = `?filter[discipline]=${filter.discipline}&filter[contribution]=${filter.contribution}&filter[criteria]=${filter.criteria}&filter[from]=${filter.from}&filter[to]=${filter.to}`;
возможно имеет смысл квери сделать объектом и прогнать сериализатором для улучшения читабельности
относится и к остальным методам

2021-11-23 08:55 UTC, euheny commented on packages/services/Layout/lib/LayoutService.js
> +import { collectionMerge, genObjectId } from '@deip/toolbox';
и как это линтер пропустил двойной импорт

2021-11-23 09:14 UTC, sholohov commented on packages/services/Layout/lib/LayoutService.js
> +import { collectionMerge, genObjectId } from '@deip/toolbox';
Ага, уже поправил. Я потом только заметил. Это при мерже конфликтов выскачило, сразу почему-то не указало, а потом на бутсрапе всё повисло, как обычно и после перезагрузки редактора ошибка уже выскочила.

2021-11-23 09:24 UTC, sholohov commented on packages/services/AppConfig/lib/AppConfigService.js
> +export class AppConfigService {
Готово

2021-11-23 09:26 UTC, sholohov commented on packages/services/ExpertiseContributions/lib/ExpertiseContributionsHttp.js
>      const query = `?filter[discipline]=${filter.discipline}&filter[contribution]=${filter.contribution}&filter[criteria]=${filter.criteria}&filter[from]=${filter.from}&filter[to]=${filter.to}`;
Согласен. Нужно будет пройтись по всем местам, где есть подобное и переписать в едином стиле через метод сериализации объекта параметров. Но я бы это сделал отдельной таской, в которой будет глобально добавляться уровень абстракции Filters

2021-11-23 09:46 UTC, sholohov commented
> ```
> import { createInstanceGetter } from '@deip/toolbox/lib/classSingleton';
> ```
> 
> сдвинуть экспорт/импорт до уровня тулбокса
> 
> ```
> import { createInstanceGetter } from '@deip/toolbox;
> ```
> 
> переименовать новый httpService - мы на рефакторинге не оставляем хвостов

Могу это сделать, но использовать деструктуризацию в таком контексте не правильно, это не правильный подход.
Диструктуризация - это синтаксический сахар, под капотом тянется весь объект и создаётся переменная.
Пример, тулбокс в нашем случае это канкатенация всех модулей в один экспорт в виде переменных у нас это конкатенировав сервисе нам нужен один модуль createInstanceGetter, мы тяем всю

2021-11-25 11:26 UTC, elena-vlasova approved these changes

2021-11-29 10:50 UTC, euheny approved these changes

2021-11-29 10:50 UTC, merged