feat(@deip/validation-plugin):fix user registration form
DEIPworld/deip-modules pull request #298
Opened 2021-11-24 19:58 UTC by Vadim-SVB

- Change Vee-validate email rule to custom rule

- Added verification of the email address by the number of entered characters

- Added new locale translation - email

![userMailFix](https://user-images.githubusercontent.com/59886821/143305386-1b476f9a-5977-48d5-b91b-95d291e173e3.png)

2021-11-25 11:59 UTC, elena-vlasova requested changes

2021-11-25 11:59 UTC, elena-vlasova commented on packages/plugins/Validation/lib/rules.js
> +      '[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+',
`-0-9` regexr пишет, что это место ломает регулярку.

2021-11-25 11:59 UTC, elena-vlasova commented on packages/plugins/Validation/lib/rules.js
> +    this.inputValueLength = value.trim().length;
Это для чего?

2021-11-26 09:27 UTC, Vadim-SVB commented on packages/plugins/Validation/lib/rules.js
> +    this.inputValueLength = value.trim().length;
это наследие прошлого что забыл выпилить, уже убрал
Спасибо за внимательность, к сожалению так иногда случается

2021-11-26 09:29 UTC, elena-vlasova reviewed
Переименуй, пожалуйста, коммит в что-то типа "...: add email validation rule". Все-таки в validation-plugin ничего не знает о форме регистрации

2021-11-29 10:47 UTC, euheny approved these changes

2021-11-29 11:15 UTC, elena-vlasova approved these changes

2021-11-29 11:18 UTC, merged