fix(@deip/fundraising-module): fix responsive for dates and amount fields
DEIPworld/deip-modules pull request #372
Opened 2022-01-13 16:15 UTC by staysey

2022-01-13 19:48 UTC, euheny requested changes

2022-01-13 19:48 UTC, euheny commented on packages/casimir/modules/fundraising/lib/components/Create/FundraisingDatesInput.vue
> +      <v-col md="6">
внимательнее читаем документацию пропсов для вьютифайных гридов. каждый пропс расчитан на респонс, поэтому допклассов на row не требуется

2022-01-13 21:36 UTC, elena-vlasova approved these changes
Мы стараемся делать так, чтобы в пре в результате оставался 1 коммит. После аппрува надо будет сосквошить 2 коммита в 1

2022-01-14 10:10 UTC, elena-vlasova approved these changes

2022-01-14 14:55 UTC, euheny approved these changes

2022-01-14 14:56 UTC, merged