refactor(@deip/validation-plugin): move rules to separate files
DEIPworld/deip-modules pull request #375
Opened 2022-01-14 14:42 UTC by staysey

2022-01-14 17:23 UTC, elena-vlasova approved these changes
Я бы еще написала unit тесты на функции validate. Расскажу, как у нас ситуацию с ними обстоит

2022-01-14 17:24 UTC, elena-vlasova commented
Конфликты. Нужно актуализировать ветку

2022-01-18 08:47 UTC, elena-vlasova submitted a review, later dismissed

2022-01-18 09:04 UTC, euheny requested changes

2022-01-18 09:04 UTC, euheny commented on packages/casimir/plugins/Validation/lib/helper.js
> +export const checkFunction = (checkedFn, parametersForFalse, parametersForTrue) => {
так же заполнить jsDoc  - редакторы лучше опишут метод в месте вызова

2022-01-18 09:04 UTC, euheny commented on packages/casimir/plugins/Validation/__tests__/dateAfter.test.js
> +    [
с точки зрения читабельности лучше объемные пропсы для функций делать константами и уже их скармливать функции
```
const forTrue = ...
const forFalse = ...
checkTwoParamsFunction(dateAfter.validate, forTrue, forFalse)
```

2022-01-18 09:04 UTC, euheny commented on packages/casimir/plugins/Validation/__tests__/dateAfter.test.js
> +    [
справедливо для остальных тестов

2022-01-18 10:54 UTC, elena-vlasova commented on jest.config.js
> +    'packages/casimir/plugins/Validation/__tests__/helper.js'
Может попробовать `packages/**/__tests__/helpers` и зарезервировать такую папку для хэлперов для тестов?
@euheny

2022-01-18 10:54 UTC, elena-vlasova commented on packages/casimir/plugins/Validation/lib/rules/dateAfter.js
> + * @param {{target: Date}}
Jsdoc, кажется,  не обработает такое
```
@param {Object} args
@param {Date} args.target
```

И док должен быть над функцией validate (правда, не уверена, что он где-нибудь тогда покажется)

2022-01-18 10:55 UTC, euheny commented on jest.config.js
> +    'packages/casimir/plugins/Validation/__tests__/helper.js'
согласен. по возможности для такого используем паттерны

2022-01-18 11:00 UTC, euheny commented on packages/casimir/plugins/Validation/lib/rules/dateAfter.js
> + * @param {{target: Date}}
я вообще про доки говорил для тестХелперов ))))
а тут да - если и делать то над валидэйтом

2022-01-18 11:00 UTC, euheny commented on packages/casimir/plugins/Validation/lib/rules/dateAfter.js
> + * @returns {Boolean} Date is after target date
примитивы пишем в ловеркейсе

2022-01-18 12:40 UTC, elena-vlasova commented on packages/casimir/plugins/Validation/__tests__/helpers/index.js
> + * @returns {boolean} returns true if two objects have the same values
Функция ничего не возвращает

2022-01-18 12:40 UTC, elena-vlasova commented on packages/casimir/plugins/Validation/__tests__/helpers/index.js
> + * @returns {boolean} returns true if two objects have the same values
И эта не возвращает

2022-01-18 12:40 UTC, elena-vlasova commented on packages/casimir/plugins/Validation/lib/rules/dateAfter.js
> + * @param {{target: Date}}
https://jsdoc.app/tags-param.html#parameters-with-properties

2022-01-18 13:48 UTC, elena-vlasova approved these changes

2022-01-18 13:55 UTC, elena-vlasova approved these changes

2022-01-18 15:10 UTC, euheny approved these changes

2022-01-18 15:10 UTC, merged