refactor(@deip/command-models): rename command-models  to commands
DEIPworld/deip-modules pull request #417
Opened 2022-02-08 12:53 UTC by staysey

2022-02-08 14:50 UTC, egor-anikey requested changes

2022-02-08 14:50 UTC, egor-anikey commented on packages/casimir/services/Assets/lib/AssetsService.js
> +} from '@deip/commands';
JsonDataMsg разве не из @deip/messages должен импортироваться ?

2022-02-08 14:50 UTC, egor-anikey commented on packages/casimir/services/Attributes/lib/AttributesService.js
> +} from '@deip/commands';
Тут тоже JsonDataMsg не из @deip/messages должен быть ? или из @deip/message-models если в этом пр еще нет пр с @deip/messages

2022-02-08 16:34 UTC, egor-anikey submitted a review, later dismissed

2022-02-09 08:33 UTC, elena-vlasova approved these changes

2022-02-09 08:33 UTC, merged