feat(@casimir/sandbox-portal): adding and removing users from team
DEIPworld/deip-modules pull request #435
Opened 2022-02-16 15:28 UTC by staysey

2022-02-18 10:20 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
> +            @click="onClickItem(user)"
`handleItemClick`

2022-02-18 10:22 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
> +            {{ userName(user) }}
Можно без дополнительного метода, сразу `$$userFullName` вызывать

2022-02-18 10:27 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
> +    </v-dialog>
У нас есть плагин для подтверждения действий. Показывает модалку с заданным сообщением и тайтлом. Возвращает promise
Пример:
``` 
const isConfirmed = await this.$confirm(
          this.$t('module.projectContent.draft.confirmPublish.message', { title: this.draft.title }),
          { title: this.$t('module.projectContent.draft.confirmPublish.title') }
        );
```

То есть можно вызвать this.$confirm  в handleItemClick, если isConfirmed === true, то вызывать removeMember

2022-02-18 10:34 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
> +        this.ready = true;
`ready` нигде не используется. Можно добавить loading и передать в кнопки удаления

2022-02-18 10:41 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
> +              memberData: this.chosenUser,
`memberData` используется только для того, чтобы в мутации удалить юзера. Лучше по payload.member в экшене получить юзера с помощью rootGetters и передать teamId и полученного юзера, а не весь payload.
Точно так же для добавления юзера

2022-02-18 10:42 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
> +        default: null
Лучше сделать `required: true`, чтобы не добавлять дополнительные проверки в коде

2022-02-18 10:43 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
> +<style lang="scss" module>
Мы используем `scoped` css

2022-02-18 10:45 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
> +  <div class="d-flex">
При большом количестве карточки вылезут за экран. Можно попробовать поиграться с VeAutoGrid

2022-02-18 10:46 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamModal/TeamModal.vue
> +            @click.stop="show=false"
Тоже стоит вынести в метод `handleCloseClick`

2022-02-18 10:47 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamModal/TeamModal.vue
> +    name: 'TeamModal',
Понятнее будет что-то типа `TeamAddMemberModal`

2022-02-18 10:47 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamModal/TeamModal.vue
> +        default: null
`required: true`

2022-02-18 10:50 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamModal/TeamModal.vue
> +            await this.$store.dispatch('teams/addTeamMember', payload);
После этого можно заэмитить ивент `success`, чтобы на стороне приложения показать нотификацию.
По возможности в компонентах с формами стараемся эмитить `success`, `cancel`, `error`

2022-02-18 10:51 UTC, elena-vlasova commented on packages/portals/sandbox-portal/src/modules/teams/components/TeamDetails/TeamDetails.vue
>          <span class="text-h6">{{ $t('teams.details.members') }}:</span>
Сделай, плиз, кнопку Invite на одной строке с заголовком у правого края

2022-02-18 11:37 UTC, euheny commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
> +<style lang="scss" module>
как минимум я не вижу причин для стилей в этом месте ) можно разойтись встроенными вещами

2022-02-21 11:50 UTC, elena-vlasova requested changes

2022-02-21 11:50 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamAddMemberModal/TeamAddMemberModal.vue
> +            @click="addMember"
`handleAddMemberClcik`

2022-02-21 11:50 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
> +      },
Забыла удалить

2022-02-21 11:50 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamAddMemberModal/TeamAddMemberModal.vue
> +          Invite member
Локализация

2022-02-21 13:29 UTC, elena-vlasova commented on packages/casimir/modules/teams/lib/components/TeamMemberCards/TeamMemberCards.vue
>        >
По идее этот div не нужен, можно все его атрибуты в v-card перенести

2022-02-22 08:43 UTC, elena-vlasova submitted a review, later dismissed

2022-02-22 08:52 UTC, elena-vlasova approved these changes

2022-02-22 08:59 UTC, merged