fix(@deip/wallet-module):fix balance card mobile view
DEIPworld/deip-modules pull request #446
Opened 2022-02-22 09:49 UTC by Vadim-SVB

* added width style to balance amount layout

![tel3](https://user-images.githubusercontent.com/59886821/155106801-bef9e461-980a-4bd8-88ec-c4ca6bcd41fe.png)

2022-02-22 13:34 UTC, euheny requested changes

2022-02-22 13:34 UTC, euheny commented on packages/casimir/modules/wallet/lib/components/Balances/BalanceCard.vue
> +            style="width:270px;"
не лучшее решение прибивать гвоздями ширину. это динамическая штука. если изменятся внешние условия, то придется помнить, что в этом месте надо править

2022-02-22 13:57 UTC, euheny commented on packages/casimir/modules/wallet/lib/components/Balances/BalanceCard.vue
> +            style="width:270px;"
`.page-content.ve-stack` - накинуть `max-width: 100%`
сразу же говорил что проблему надо искать в родителях

2022-02-23 10:23 UTC, Vadim-SVB commented on packages/casimir/modules/wallet/lib/components/Balances/BalanceCard.vue
> +            style="width:270px;"
гениально

2022-02-23 16:04 UTC, elena-vlasova requested changes

2022-02-23 16:04 UTC, elena-vlasova commented on packages/casimir/modules/wallet/lib/components/Balances/BalanceCard.vue
> +  .page-content.ve-stack {
Это класс не из этого компонента. Нельзя тут стили задавать

2022-02-23 16:04 UTC, elena-vlasova requested changes

2022-02-23 16:04 UTC, elena-vlasova commented on packages/casimir/modules/wallet/lib/components/Balances/BalanceCard.vue
> +</style>
Это класс не из этого компонента. Нельзя тут стили задавать

2022-02-23 17:25 UTC, euheny commented on packages/casimir/modules/wallet/lib/components/Balances/BalanceCard.vue
> +</style>
как минимум для этого надо найти где данный класс, посмотреть есть ли он еще где-то и, скорее всего, если для этого класса уже есть стили - тупо добавить, а не создавать стиль черте знает где да еще и в конкатинации

2022-02-24 09:54 UTC, closed without merging