Move constants to @deip/constants
DEIPworld/deip-modules pull request #85
Opened 2021-07-13 07:33 UTC by McWild

Move constants from modules to  @deip/constants

2021-07-13 11:01 UTC, elena-vlasova commented
Лучше делать pull c --rebase, чтобы не было лишних коммитов `Merge branch 'develop' into constants`

2021-07-13 11:13 UTC, euheny reviewed
@elena-vlasova @egortsaryk9 прошу так же пройтись по коду

2021-07-13 11:13 UTC, euheny commented on packages/modules/attributes/lib/components/attribute-set.js
> +import { ATTR_TYPES, ATTR_TYPES_SET_RULES, ATTR_TYPES_SET_SCHEMAS } from '@deip/constants';
думаю схемы лучше вернуть в модуль, так как это всетки функциональное зло и там могжет быть сложная логика и генераторы, которые в константах не нужны

2021-07-13 11:13 UTC, euheny commented on packages/modules/teams/index.js
> +export { TEAM_FORM_MODES } from '@deip/constants';
удалить и заменить на FORM_MODES

2021-07-13 11:13 UTC, euheny commented on packages/modules/teams/lib/components/TeamForm.vue
> +  import { TEAM_FORM_MODES } from '@deip/constants';
удалить и заменить на FORM_MODES

2021-07-13 11:13 UTC, euheny commented on packages/services/Access/lib/AccessService.js
> +  ACCESS_TOKEN_KEY = ACCESS_TOKEN_KEY;
в целом не обязательно забрасывать константы в контекст класса. можно юзать и извне. new Class() в любом случае не имеет шанса их изменить

2021-07-13 11:13 UTC, euheny commented on packages/services/Attributes/index.js
> +export {
холостой реэкспорт

2021-07-13 11:13 UTC, euheny commented on packages/services/Chain/index.js
> +export {
холостой реэкспорт

2021-07-13 11:13 UTC, euheny commented on packages/services/Chain/lib/impl/substrate/ChainTypes.js
> +export { CHAIN_TYPES as default } from '@deip/constants';
подозреваю что надо вернуть. @egortsaryk9 что скажешь ?

2021-07-13 11:13 UTC, euheny commented on packages/services/Grants/index.js
> +export {
холостой реэкспорт

2021-07-13 11:13 UTC, euheny commented on packages/services/ResearchContent/index.js
> +export { RESEARCH_CONTENT_TYPES } from '@deip/constants';
холостой реэкспорт

2021-07-13 11:13 UTC, euheny commented on packages/services/ResearchContentReviews/index.js
> +export { ASSESSMENT_CRITERIA_TYPE } from '@deip/constants';
холостой реэкспорт

2021-07-13 11:13 UTC, euheny commented on packages/services/User/index.js
> +export {
холостой реэкспорт

2021-07-13 11:13 UTC, euheny commented on packages/utilities/constants/lib/attributes.js
> +const ATTR_TYPES_SET_RULES = {
схемы аернуть в модуль. рулы скорее всего тоже, так как за пределами модуля они пользоваться не будут. @elena-vlasova твое мнение?

2021-07-13 11:18 UTC, elena-vlasova commented on packages/utilities/constants/lib/attributes.js
> +const ATTR_TYPES_SET_RULES = {
Согласна

2021-07-13 11:19 UTC, elena-vlasova commented on packages/utilities/constants/lib/project.js
> +const PROJECT_APPLICATION_STATUS = {
Наверно стоит сделать через createEnum

2021-07-13 11:32 UTC, egortsaryk9 commented on packages/services/Chain/lib/impl/substrate/ChainTypes.js
> +export { CHAIN_TYPES as default } from '@deip/constants';
да, это надо обязательно вернуть в substrate, это реестр типов в substrate - chain, сугубо внутренняя штука, никогда не будет экспортироваться за пределы папки substrate

2021-07-13 11:37 UTC, egortsaryk9 commented on packages/modules/attributes/lib/components/attribute-set.js
> +import { ATTR_TYPES, ATTR_TYPES_SET_RULES, ATTR_TYPES_SET_SCHEMAS } from '@deip/constants';
согласен

2021-07-13 11:55 UTC, euheny commented on packages/utilities/constants/lib/project.js
> +const PROJECT_APPLICATION_STATUS = {
@egortsaryk9 у нас на бэке статус апликейшенов интовый или стринговый? тут согласен с @elena-vlasova, что такие вещи лучше интовыми.

2021-07-14 06:56 UTC, euheny commented on packages/modules/attributes/lib/components/attribute-set.js
> +const avatarMask = `
схемы вынести в отдельный файл. они будут разрастаться и держать это в файле компонента напряжно

2021-07-14 06:56 UTC, euheny commented on packages/utilities/constants/lib/chain.js
> +// TODO:  Keep it sync with APP_CMD enum and replace it with APP_CMD enum completely
@egortsaryk9 что тут имелось в виду?

2021-07-14 11:12 UTC, egortsaryk9 commented on packages/utilities/constants/lib/chain.js
> +// TODO:  Keep it sync with APP_CMD enum and replace it with APP_CMD enum completely
Имелось ввиду что PROTOCOL_OPERATIONS_MAP должен иметь такие же цифры как и APP_CMD. Было продублировано из-за кросс-референса. Если проблемы больше нет то можно заменить его usages на APP_CMD

2021-07-14 11:16 UTC, euheny commented on packages/utilities/constants/lib/chain.js
> +// TODO:  Keep it sync with APP_CMD enum and replace it with APP_CMD enum completely
ок. след комитом/рефакторингом

2021-07-14 11:35 UTC, elena-vlasova commented on packages/modules/attributes/lib/schemas/attribute-set-schema.js
> +import {
`attribute-set-schema.js` 
@euheny мы файлы называем кэмэлкейсом или нет?

2021-07-14 11:43 UTC, elena-vlasova requested changes

2021-07-14 11:43 UTC, elena-vlasova commented on packages/modules/fundraising/lib/components/Contribute/AmountSelector.vue
> +  import { NUMBER_OF_STEPS } from '@deip/constants';
Сорри, в прошлый раз проглядела. Это не надо было выносить

2021-07-14 11:43 UTC, elena-vlasova commented on packages/modules/fundraising/lib/components/Create/CreateFundraisingForm.vue
> -        const DEFAULT_PRECISION = 0;
И это не надо было выносить, они дефолтные только для этого метода.

2021-07-14 11:43 UTC, elena-vlasova commented on packages/services/Investments/index.js
> +export { TS_TYPES } from '@deip/constants';
Реэкспорт

2021-07-14 11:43 UTC, elena-vlasova commented on packages/utilities/constants/lib/fundraising.js
> +const DEFAULT_AMOUNT = 10000;
Все, кроме MIN_TOKEN_UNITS_TO_SELL, надо убрать из общих констант

2021-07-14 11:51 UTC, euheny commented on packages/modules/attributes/lib/schemas/attribute-set-schema.js
> +import {
медленно и уверенно все перееден на paramCase. мне заманало думать в каком кейсе что именовать. глядя на тот же вьютифай там вообще три кейса в именовании и хер пойми какой-когда и почему

2021-07-14 12:36 UTC, elena-vlasova approved these changes

2021-07-14 21:33 UTC, merged